name: CustomPlugin
version: '0.2'
main: io.github.VoidMatterRules.customPlugin.Main
api-version: '1.21'

commands:
   HealTestCommand:
      description: "Heals the player"
      usage: "/heal"
   Kit:
      description: "Opens a Kit Inventory"
      usage: "/kit"